name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Run Tests
      run: |
        go test ./...

    - name: Build CLI
      if: contains(github.event.head_commit.message, '[cli]')
      run: |
        go build -o bin/ccv ./cmd/cli

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_type == 'tag'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Build CLI for Release
      run: |
        go build -o bin/ccv ./cmd/cli

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/ccv
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}